export const SET_CURRENT_STEP = 'SET_CURRENT_STEP';
export const MAKE_APPOINTMENT = 'MAKE_APPOINTMENT';
export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM';
export const SET_DATA_PICKER = 'SET_DATA_PICKER';
export const SET_SELECTED_TIME = 'SET_SELECTED_TIME';
export const SET_ORDER_TIME = 'SET_ORDER_TIME';
export const KEEP_SELECTED_ITEM = 'KEEP_SELECTED_ITEM';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_SELECT_DATE = 'SET_SELECT_DATE';





