export const SET_CURRENT_STEP = 'SET_CURRENT_STEP';
export const SET_DATA_PICKER = 'SET_DATA_PICKER';
export const SET_SELECTED_TIME = 'SET_SELECTED_TIME'; 
export const KEEP_SELECTED_ITEM = 'KEEP_SELECTED_ITEM';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_ORDER_NAME = 'SET_ORDER_NAME';
export const SET_ORDER_DATE = 'SET_ORDER_DATE';
export const SET_ORDER_TIME = 'SET_ORDER_TIME';
export const SET_ORDER_PERSONAL_INFO = 'SET_ORDER_PERSONAL_INFO';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const SET_TMP_TIME = 'SET_TMP_TIME';
export const GET_ORDEREDTIME = 'GET_ORDEREDTIME';













